server:
  port: 8888

spring:
  application:
    name: cloud-config
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config

eureka:
  client:
    serviceUrl:
#      defaultZone: http://localhost:${server.port}/eureka/
      defaultZone: http://eurekaserver1:8900/eureka/,http://eurekaserver2:8900/eureka/
    instance:
      hostname: cloud-config

management:
  security:
    enabled: false