server:
  port: 9000
  context-path: /

spring:
  application:
    name: cloud-admin
  thymeleaf:
    mode: LEGACYHTML5
    cache: false

logging:
  file: /rbac.log
  level:
    root: INFO
    com:
      teradata:
        dao: debug
mybatis:
  configuration:
    mapUnderscoreToCamelCase: true
  mapper-locations: classpath:mapper/*
  type-aliases-package: com.teradata.bean

management:
  security:
    enabled: false

---
spring:
  profiles:
    active: prod
  cloud:
    config:
      label: master
      profile: prod
      discovery:
        enabled: true
        service-id: cloud-config
eureka:
  client:
    serviceUrl:
      defaultZone: http://eurekaserver1:8900/eureka/,http://eurekaserver2:8900/eureka/

---
spring:
  profiles: dev
  cloud:
    config:
      label: master
      profile: dev
      uri: http://localhost:8888/
eureka:
  client:
    serviceUrl:
      defaultZone: http\://localhost\:8761/eureka/


